services:
  dashboard-engine:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dashboard-engine
    ports:
      - "8000:8000"
    volumes:
      - D:/shared/data:/data
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
