[project]
name = "dashboard"
version = "0.1.0"
description = ""
authors = [{ name = "Taj Eddine Marmoul", email = "tajdinetajdine1@gmail.com" }]
readme = "README.md"
requires-python = ">=3.9,<3.14"
dependencies = [
    "dash (>=3.1.1,<4.0.0)",
    "polars (>=1.31.0,<2.0.0)",
    "pyinstaller (>=6.14.2,<7.0.0)",
    "dash-bootstrap-components (>=2.0.3,<3.0.0)",
    "platformdirs (>=4.3.8,<5.0.0)",
    "toml (>=0.10.2,<0.11.0)",
    "fastexcel (>=0.14.0,<0.15.0)",
    "pyarrow (>=20.0.0,<21.0.0)",
    "xlsxwriter (>=3.2.5,<4.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"
